-- CreateTable
CREATE TABLE `Auth` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `status` ENUM('ACTIVE', 'EXPIRE') NOT NULL DEFAULT 'ACTIVE',
    `token` LONGTEXT NULL,
    `refreshToken` LONGTEXT NULL,
    `type` ENUM('GOOGLE') NOT NULL DEFAULT 'GOOGLE',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
