-- AlterTable
ALTER TABLE `Crawling` MODIFY `type` ENUM('EASYSHOP', 'EASYSHOP_SALES') NOT NULL DEFAULT 'EASYSHOP';

-- AlterTable
ALTER TABLE `CrawlingInfo` MODIFY `type` ENUM('EASYSHOP', 'EASYSHOP_SALES') NOT NULL DEFAULT 'EASYSHOP';
