-- CreateTable
CREATE TABLE `CardInfos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `userId` INTEGER NULL,
    `type` ENUM('EASYSHOP', 'CREDIT_FINANCE') NOT NULL DEFAULT 'EASYSHOP',
    `cardCompanyName` ENUM('BC_CARD', 'KB_CARD', 'HANA_CARD', 'HYUNDAE_CARD', 'SHINHAN_CARD', 'SAMSUNG_CARD', 'NH_CARD', 'LOTTE_CARD', 'HDO_CARD') NULL,
    `commisionRate` INTEGER NOT NULL DEFAULT 0,
    `creditCardRate` INTEGER NOT NULL DEFAULT 0,
    `checkCardRate` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CardInfos` ADD CONSTRAINT `CardInfos_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
