-- AlterTable
ALTER TABLE `CardInfos` MODIFY `type` ENUM('EASYSHOP', 'CREDIT_FINANCE', 'INNOPAY') NOT NULL DEFAULT 'EASYSHOP';

-- AlterTable
ALTER TABLE `Crawling` MODIFY `type` ENUM('EASYSHOP', 'CREDIT_FINANCE', 'INNOPAY') NOT NULL DEFAULT 'EASYSHOP';

-- AlterTable
ALTER TABLE `CrawlingInfo` MODIFY `type` ENUM('EASYSHOP', 'CREDIT_FINANCE', 'INNOPAY') NOT NULL DEFAULT 'EASYSHOP';
