-- AlterTable
ALTER TABLE `Bond` MODIFY `vanType` ENUM('KICC') NULL DEFAULT 'KICC';

-- AlterTable
ALTER TABLE `BondDeposit` MODIFY `vanType` ENUM('KICC') NULL DEFAULT 'KICC';

-- AlterTable
ALTER TABLE `Crawling` MODIFY `type` ENUM('EASYSHOP', 'CREDIT_FINANCE') NOT NULL DEFAULT 'EASYSHOP';

-- AlterTable
ALTER TABLE `CrawlingInfo` MODIFY `type` ENUM('EASYSHOP', 'CREDIT_FINANCE') NOT NULL DEFAULT 'EASYSHOP';
