name: CD for prod

concurrency:
  group: cd-for-prod
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_PROD_KEY }}
          host: ${{ secrets.AWS_PROD_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          script: |
            ./prod-deploy.sh
